kind: Route
apiVersion: route.openshift.io/v1
metadata:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
spec:
    to:
        kind: Service
        name: hello-world-spring-boot-helm
        weight: 100
    port:
        targetPort: http
    tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None